### ISSUE TITLE
Best parameters for training CaloGAN

### ISSUE THREAD

**Issue by OswaldoBornemann** [hep-lbdl/CaloGAN#12]
What is the best parameters for reproducing the experimental result while training CaloGAN ?

I have trained CaloGAN on dataset eplus.hdf5, but the results using epoch 50 seem worse.

![Screen Shot 2023-02-12 at 2 42 41 PM copy](https://user-images.githubusercontent.com/11624203/218297082-e8d94a8c-23b5-4ca2-a3aa-24418e79e4b2.jpg)

**Comment by bnachman** [comment]
Hello @OswaldoBornemann I am sorry for taking so long to respond; thank you for your interest in our work!  CaloGAN is now rather old - I'd suggest you take a look at one of the newest models like CaloScore (https://github.com/ViniciusMikuni/CaloScore) - that repo also has a (W)GAN for comparison.
